name: Build
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: develop
        required: true
        description: branch name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: build image
        run: docker build ./src/ -t shiou278/test-actions:latest
      - name: push image
        run: docker push shiou278/test-actions:latest
