name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./src/ -t shiou278/test-actions:latest
      - name: push image
        run: docker push shiou278/test-actions:latest
